# Site settings
title: Braincode Mobi
menu: false

baseurl: ""
url: "http://braincode.mobi"
twitter_username: AllegroTechBlog
github_username:  allegro

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
    input: GFM
    coderay_line_numbers: nil
permalink: /:title.html

